### ISSUE TITLE
Publish to an ELPA

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/sx.el#109]
Now that `v0.1` has been tagged, we should figure for a way to get this to people.

## Tasks
- [x] Update the README
- [x] Fix various compilation bugs #115 
- [x] Autoload sx-tab-frontpage
- [x] … ?
- [x] Profit

**Comment by vermiculus** [comment]
Since #151 is now fixed, I'm closing this issue. The Info manual can be made into a separate issue.
